#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v2
# autospec commit: e661f3a
#
Name     : libcmis
Version  : 0.6.1
Release  : 12
URL      : https://dev-www.libreoffice.org/src/libcmis-0.6.1.tar.xz
Source0  : https://dev-www.libreoffice.org/src/libcmis-0.6.1.tar.xz
Summary  : CMIS protocol client library
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1 MPL-1.1
Requires: libcmis-bin = %{version}-%{release}
Requires: libcmis-lib = %{version}-%{release}
Requires: libcmis-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-configure
BuildRequires : cppcheck
BuildRequires : pkgconfig(cppunit)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libxml-2.0)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
[![Build Status](https://travis-ci.org/tdf/libcmis.svg?branch=master)](https://travis-ci.org/tdf/libcmis)
[![Total alerts](https://img.shields.io/lgtm/alerts/g/tdf/libcmis.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/tdf/libcmis/alerts/)
[![Coverity Scan](https://scan.coverity.com/projects/17516/badge.svg)](https://scan.coverity.com/projects/tdf-libcmis)

%package bin
Summary: bin components for the libcmis package.
Group: Binaries
Requires: libcmis-license = %{version}-%{release}

%description bin
bin components for the libcmis package.


%package dev
Summary: dev components for the libcmis package.
Group: Development
Requires: libcmis-lib = %{version}-%{release}
Requires: libcmis-bin = %{version}-%{release}
Provides: libcmis-devel = %{version}-%{release}
Requires: libcmis = %{version}-%{release}

%description dev
dev components for the libcmis package.


%package lib
Summary: lib components for the libcmis package.
Group: Libraries
Requires: libcmis-license = %{version}-%{release}

%description lib
lib components for the libcmis package.


%package license
Summary: license components for the libcmis package.
Group: Default

%description license
license components for the libcmis package.


%prep
%setup -q -n libcmis-0.6.1
cd %{_builddir}/libcmis-0.6.1
pushd ..
cp -a libcmis-0.6.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1701115527
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%configure --disable-static --without-man --disable-werror
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
%configure --disable-static --without-man --disable-werror
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :
cd ../buildavx2;
make %{?_smp_mflags} check || : || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1701115527
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libcmis
cp %{_builddir}/libcmis-%{version}/COPYING.GPL %{buildroot}/usr/share/package-licenses/libcmis/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/libcmis-%{version}/COPYING.LGPL %{buildroot}/usr/share/package-licenses/libcmis/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
cp %{_builddir}/libcmis-%{version}/COPYING.MPL %{buildroot}/usr/share/package-licenses/libcmis/6b6d141fcb498eda127af240db4045d2aa53bb42 || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/cmis-client
/usr/bin/cmis-client

%files dev
%defattr(-,root,root,-)
/usr/include/libcmis-0.6/libcmis/allowable-actions.hxx
/usr/include/libcmis-0.6/libcmis/document.hxx
/usr/include/libcmis-0.6/libcmis/exception.hxx
/usr/include/libcmis-0.6/libcmis/folder.hxx
/usr/include/libcmis-0.6/libcmis/libcmis-api.h
/usr/include/libcmis-0.6/libcmis/libcmis.hxx
/usr/include/libcmis-0.6/libcmis/oauth2-data.hxx
/usr/include/libcmis-0.6/libcmis/object-type.hxx
/usr/include/libcmis-0.6/libcmis/object.hxx
/usr/include/libcmis-0.6/libcmis/property-type.hxx
/usr/include/libcmis-0.6/libcmis/property.hxx
/usr/include/libcmis-0.6/libcmis/rendition.hxx
/usr/include/libcmis-0.6/libcmis/repository.hxx
/usr/include/libcmis-0.6/libcmis/session-factory.hxx
/usr/include/libcmis-0.6/libcmis/session.hxx
/usr/include/libcmis-0.6/libcmis/xml-utils.hxx
/usr/include/libcmis-0.6/libcmis/xmlserializable.hxx
/usr/include/libcmis-c-0.6/libcmis-c/allowable-actions.h
/usr/include/libcmis-c-0.6/libcmis-c/document.h
/usr/include/libcmis-c-0.6/libcmis-c/error.h
/usr/include/libcmis-c-0.6/libcmis-c/folder.h
/usr/include/libcmis-c-0.6/libcmis-c/libcmis-c-api.h
/usr/include/libcmis-c-0.6/libcmis-c/libcmis-c.h
/usr/include/libcmis-c-0.6/libcmis-c/oauth2-data.h
/usr/include/libcmis-c-0.6/libcmis-c/object-type.h
/usr/include/libcmis-c-0.6/libcmis-c/object.h
/usr/include/libcmis-c-0.6/libcmis-c/property-type.h
/usr/include/libcmis-c-0.6/libcmis-c/property.h
/usr/include/libcmis-c-0.6/libcmis-c/rendition.h
/usr/include/libcmis-c-0.6/libcmis-c/repository.h
/usr/include/libcmis-c-0.6/libcmis-c/session-factory.h
/usr/include/libcmis-c-0.6/libcmis-c/session.h
/usr/include/libcmis-c-0.6/libcmis-c/types.h
/usr/include/libcmis-c-0.6/libcmis-c/vectors.h
/usr/lib64/libcmis-0.6.so
/usr/lib64/libcmis-c-0.6.so
/usr/lib64/pkgconfig/libcmis-0.6.pc
/usr/lib64/pkgconfig/libcmis-c-0.6.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libcmis-0.6.so.5.1.0
/V3/usr/lib64/libcmis-c-0.6.so.6.0.0
/usr/lib64/libcmis-0.6.so.5
/usr/lib64/libcmis-0.6.so.5.1.0
/usr/lib64/libcmis-c-0.6.so.6
/usr/lib64/libcmis-c-0.6.so.6.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libcmis/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/libcmis/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/libcmis/6b6d141fcb498eda127af240db4045d2aa53bb42
