#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libcmis
Version  : 0.5.2
Release  : 6
URL      : https://dev-www.libreoffice.org/src/libcmis-0.5.2.tar.xz
Source0  : https://dev-www.libreoffice.org/src/libcmis-0.5.2.tar.xz
Summary  : CMIS protocol client library
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1 MPL-1.1
Requires: libcmis-bin = %{version}-%{release}
Requires: libcmis-lib = %{version}-%{release}
Requires: libcmis-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : cppcheck
BuildRequires : pkgconfig(cppunit)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libxml-2.0)

%description
No detailed description available

%package bin
Summary: bin components for the libcmis package.
Group: Binaries
Requires: libcmis-license = %{version}-%{release}

%description bin
bin components for the libcmis package.


%package dev
Summary: dev components for the libcmis package.
Group: Development
Requires: libcmis-lib = %{version}-%{release}
Requires: libcmis-bin = %{version}-%{release}
Provides: libcmis-devel = %{version}-%{release}
Requires: libcmis = %{version}-%{release}

%description dev
dev components for the libcmis package.


%package lib
Summary: lib components for the libcmis package.
Group: Libraries
Requires: libcmis-license = %{version}-%{release}

%description lib
lib components for the libcmis package.


%package license
Summary: license components for the libcmis package.
Group: Default

%description license
license components for the libcmis package.


%prep
%setup -q -n libcmis-0.5.2
cd %{_builddir}/libcmis-0.5.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1592454636
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static --without-man --disable-werror
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1592454636
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libcmis
cp %{_builddir}/libcmis-0.5.2/COPYING.GPL %{buildroot}/usr/share/package-licenses/libcmis/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/libcmis-0.5.2/COPYING.LGPL %{buildroot}/usr/share/package-licenses/libcmis/01a6b4bf79aca9b556822601186afab86e8c4fbf
cp %{_builddir}/libcmis-0.5.2/COPYING.MPL %{buildroot}/usr/share/package-licenses/libcmis/6b6d141fcb498eda127af240db4045d2aa53bb42
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cmis-client

%files dev
%defattr(-,root,root,-)
/usr/include/libcmis-0.5/libcmis/allowable-actions.hxx
/usr/include/libcmis-0.5/libcmis/document.hxx
/usr/include/libcmis-0.5/libcmis/exception.hxx
/usr/include/libcmis-0.5/libcmis/folder.hxx
/usr/include/libcmis-0.5/libcmis/libcmis-api.h
/usr/include/libcmis-0.5/libcmis/libcmis.hxx
/usr/include/libcmis-0.5/libcmis/oauth2-data.hxx
/usr/include/libcmis-0.5/libcmis/object-type.hxx
/usr/include/libcmis-0.5/libcmis/object.hxx
/usr/include/libcmis-0.5/libcmis/property-type.hxx
/usr/include/libcmis-0.5/libcmis/property.hxx
/usr/include/libcmis-0.5/libcmis/rendition.hxx
/usr/include/libcmis-0.5/libcmis/repository.hxx
/usr/include/libcmis-0.5/libcmis/session-factory.hxx
/usr/include/libcmis-0.5/libcmis/session.hxx
/usr/include/libcmis-0.5/libcmis/xml-utils.hxx
/usr/include/libcmis-0.5/libcmis/xmlserializable.hxx
/usr/include/libcmis-c-0.5/libcmis-c/allowable-actions.h
/usr/include/libcmis-c-0.5/libcmis-c/document.h
/usr/include/libcmis-c-0.5/libcmis-c/error.h
/usr/include/libcmis-c-0.5/libcmis-c/folder.h
/usr/include/libcmis-c-0.5/libcmis-c/libcmis-c-api.h
/usr/include/libcmis-c-0.5/libcmis-c/libcmis-c.h
/usr/include/libcmis-c-0.5/libcmis-c/oauth2-data.h
/usr/include/libcmis-c-0.5/libcmis-c/object-type.h
/usr/include/libcmis-c-0.5/libcmis-c/object.h
/usr/include/libcmis-c-0.5/libcmis-c/property-type.h
/usr/include/libcmis-c-0.5/libcmis-c/property.h
/usr/include/libcmis-c-0.5/libcmis-c/rendition.h
/usr/include/libcmis-c-0.5/libcmis-c/repository.h
/usr/include/libcmis-c-0.5/libcmis-c/session-factory.h
/usr/include/libcmis-c-0.5/libcmis-c/session.h
/usr/include/libcmis-c-0.5/libcmis-c/types.h
/usr/include/libcmis-c-0.5/libcmis-c/vectors.h
/usr/lib64/libcmis-0.5.so
/usr/lib64/libcmis-c-0.5.so
/usr/lib64/pkgconfig/libcmis-0.5.pc
/usr/lib64/pkgconfig/libcmis-c-0.5.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcmis-0.5.so.5
/usr/lib64/libcmis-0.5.so.5.0.0
/usr/lib64/libcmis-c-0.5.so.5
/usr/lib64/libcmis-c-0.5.so.5.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libcmis/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/libcmis/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/libcmis/6b6d141fcb498eda127af240db4045d2aa53bb42
